# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.belink.com:
  orderer1.belink.com:
  peer0.blockchain.belink.com:
  peer1.blockchain.belink.com:
  peer0.blockchain.xinwang.com:
  peer1.blockchain.xinwang.com:
  peer0.blockchain.keshang.com:
  peer1.blockchain.keshang.com:

networks:
  byfn:

services:

  zookeeper0:
    extends:
      file: base/dc-orderer-kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - byfn

  zookeeper1:
    extends:
      file: base/dc-orderer-kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 2191:2181
      - 2898:2888
      - 3898:3888
    networks:
      - byfn

  zookeeper2:
    extends:
      file: base/dc-orderer-kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 2101:2181
      - 2808:2888
      - 3808:3888
    networks:
      - byfn

  kafka0:
    extends:
      file: base/dc-orderer-kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - byfn

  kafka1:
    extends:
      file: base/dc-orderer-kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 9192:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - byfn

  kafka2:
    extends:
      file: base/dc-orderer-kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 9292:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - byfn

  kafka3:
    extends:
      file: base/dc-orderer-kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    ports:
      - 9392:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - byfn

  orderer.belink.com:
    container_name: orderer.belink.com
    extends:
      file: base/dc-orderer-base.yaml
      service: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/belink.com/orderers/orderer.belink.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/belink.com/orderers/orderer.belink.com/tls/:/var/hyperledger/orderer/tls
      - orderer.belink.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - byfn

  orderer1.belink.com:
    container_name: orderer1.belink.com
    extends:
      file: base/dc-orderer-base.yaml
      service: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/belink.com/orderers/orderer1.belink.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/belink.com/orderers/orderer1.belink.com/tls/:/var/hyperledger/orderer/tls
      - orderer1.belink.com:/var/hyperledger/production/orderer
    ports:
      - 17050:7050
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - byfn

  peer0.blockchain.belink.com:
    container_name: peer0.blockchain.belink.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.blockchain.belink.com
    networks:
      - byfn

  peer1.blockchain.belink.com:
    container_name: peer1.blockchain.belink.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.blockchain.belink.com
    networks:
      - byfn

  peer0.blockchain.xinwang.com:
    container_name: peer0.blockchain.xinwang.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.blockchain.xinwang.com
    networks:
      - byfn

  peer1.blockchain.xinwang.com:
    container_name: peer1.blockchain.xinwang.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.blockchain.xinwang.com
    networks:
      - byfn

  peer0.blockchain.keshang.com:
    container_name: peer0.blockchain.keshang.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.blockchain.keshang.com
    networks:
      - byfn

  peer1.blockchain.keshang.com:
    container_name: peer1.blockchain.keshang.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.blockchain.keshang.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.blockchain.belink.com:7051
      - CORE_PEER_LOCALMSPID=BelinkMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blockchain.belink.com/peers/peer0.blockchain.belink.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blockchain.belink.com/peers/peer0.blockchain.belink.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blockchain.belink.com/peers/peer0.blockchain.belink.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blockchain.belink.com/users/Admin@blockchain.belink.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.belink.com
      - orderer1.belink.com
      - peer0.blockchain.belink.com
      - peer1.blockchain.belink.com
      - peer0.blockchain.xinwang.com
      - peer1.blockchain.xinwang.com
      - peer0.blockchain.keshang.com
      - peer1.blockchain.keshang.com
    networks:
      - byfn
